# #
# # global
# #
# # global:
# #   project: default
# #   repoUrl: https://github.com/sebolabs/eks-tf-gitops # TODO: make sure your git repo matches here
# #   targetRevision: release-1-2-0 # TODO: make sure your branch matches here
# #   clusterName: seminc-test-k8s # TODO: make sure your cluster name matches here
# #   region: eu-central-1 # TODO: make sure your region matches here
# #   namespace: kube-system

# #
# # aws-cloudwatch-metrics
# #
# awsCloudWatchMetrics:
#   serviceAccountName: aws-cloudwatch-metrics-sa # managed by Terraform

# #
# # aws-efs-csi-driver
# #
# awsEfsCsiDriver:
#   serviceAccountName: efs-csi-sa # managed by Terraform

# #
# # aws-for-fluent-bit
# #
awsForFluentBit:
  kinesis:
    enabled: false
  firehose:
    enabled: false
  elasticsearch:
    enabled: false
#   serviceAccountName: aws-for-fluent-bit-sa # managed by Terraform

# #
# # aws-load-balancer-controller
# #
# awsLoadBalancerController:
#   serviceAccountName: aws-load-balancer-controller-sa # managed by Terraform

# #
# # cluster-autoscaler
# #
# clusterAutoscaler:
#   serviceAccountName: cluster-autoscaler-sa # managed by Terraform

# #
# # csi-secrets-store-provider-aws
# #
# # csiSecretsStoreProviderAws:

# #
# # external-dns
# #
# externalDns:
#   serviceAccountName: external-dns-sa # managed by Terraform

# #
# # metrics-server
# #
# # metricsServer:
