global:
  project: default
  repoUrl: https://github.com/sebolabs/eks-tf-gitops
  targetRevision: release-1-2-0
  clusterName: seminc-test-k8s
  region: eu-central-1
  namespace: kube-system

awsCloudWatchMetrics:
  enable: false
  serviceAccountName: aws-cloudwatch-metrics-sa # managed by Terraform

awsEfsCsiDriver:
  enable: false
  serviceAccountName: efs-csi-sa # managed by Terraform

awsForFluentBit:
  enable: true
  serviceAccountName: aws-for-fluent-bit-sa # managed by Terraform

awsLoadBalancerController:
  enable: true
  serviceAccountName: aws-load-balancer-controller-sa

clusterAutoscaler:
  enable: false
  serviceAccountName: cluster-autoscaler-sa # managed by Terraform

csiSecretsStoreProviderAws:
  enable: false

externalDns:
  enable: true
  serviceAccountName: external-dns-sa

metricsServer:
  enable: false
