{{- if and (.Values.awsForFluentBit) (.Values.awsForFluentBit.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-for-fluent-bit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ .Values.global.repoUrl }}
    path: k8s/add-ons/aws-for-fluent-bit
    targetRevision: {{ .Values.global.targetRevision }}
    helm:
      values: |
        aws-for-fluent-bit:
        {{- toYaml .Values.awsForFluentBit | nindent 10 }}
      parameters:
      - name: aws-for-fluent-bit.cloudWatch.region
        value: {{ .Values.global.region }}
      - name: aws-for-fluent-bit.serviceAccount.name
        value: {{ .Values.awsForFluentBit.serviceAccountName }}
      - name: aws-for-fluent-bit.cloudWatch.serviceAccount.name
        value: {{ .Values.awsForFluentBit.serviceAccountName }}
      - name: aws-for-fluent-bit.cloudWatch.logGroupName
        value: {{ .Values.awsForFluentBit.logGroupName }}
      - name: aws-for-fluent-bit.firehose.enabled
        value: {{ .Values.awsForFluentBit.firehose.enabled}}
      - name: aws-for-fluent-bit.firehose.region
        value: {{ .Values.global.region }}
      - name: aws-for-fluent-bit.kinesis.enabled
        value: {{ .Values.awsForFluentBit.kinesis.enabled}}
      - name: aws-for-fluent-bit.kinesis.region
        value: {{ .Values.global.region }}
      - name: aws-for-fluent-bit.elasticsearch.enabled
        value: {{ .Values.awsForFluentBit.elasticsearch.enabled}}
      - name: aws-for-fluent-bit.elasticsearch.region
        value: {{ .Values.global.region }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespace }}
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
