{{- if and (.Values.metricsServer) (.Values.metricsServer.enable) -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoUrl }}
    path: k8s/add-ons/metrics-server
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        metrics-server:
        {{- toYaml .Values.metricsServer | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
    retry:
      limit: 1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
{{- end -}}
