apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '!kube-system'
      server: '*'
    - namespace: '{{ .Values.environment }}-*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - '{{ .Values.environment }}-*'
